### ISSUE TITLE
The order of last 6 parameters

### ISSUE THREAD

**Issue by zhipeng-fan** [Juyong/3DFace#10]
Hi, I am wondering how is the last 6 parameters ordered for the 185 parameters? I suppose it should be pitch, yaw, roll, t_x, t_y and s. In that case, how could we convert the float number of pitch, yaw and roll to the degrees? Thanks!

**Comment by YudongGuo** [comment]
Yes, the 6 parameters are pitch, yaw, roll, t_x, t_y and s. The float numbers of pitch, yaw, row are radians and you can use the provided sample code to get rotation matrix.
