### ISSUE TITLE
How can we get the 3DMM parameters as you given to us?

### ISSUE THREAD

**Issue by 724566247** [Juyong/3DFace#13]
We can see that the 3DMM parameters you given to us in your dataset is very accurate.I find some open source code in the website and I want to recover the parameters of any face, but all of them can not get accurate parameters as you.Could you give us the source code of geting the 3DMM parameters of faces?Thanks a lot!

**Comment by YudongGuo** [comment]
Thanks for your appreciation, but we couldn't provide the source code. You can implement the 3DMM fitting part to get the 3DMM parameters.
