### ISSUE TITLE
Links for Dataset and BFM

### ISSUE THREAD

**Issue by mojoee** [Juyong/3DFace#19]
Thanks for the sharing of your great work. I wanted to replicate your experiments, but it seems that the links for the datasets that you used in the paper and for the BFM on your github description are expired. Could you help out?

**Comment by YudongGuo** [comment]
Hi, thanks for pointing out this. I just checked the links and found that only the BFM link expired. I have updated the BFM link.

**Comment by mojoee** [comment]
Thanks for the quick help.
