### ISSUE TITLE
Why the vertex number is Inconsistent with FaceWarehouse?

### ISSUE THREAD

**Issue by yangpeinmgdx** [Juyong/3DFace#20]
Hi, I have down load Exp_Pca.bin, and found that the vertex number is much larger than FaceWarehouse, in which each face mesh has 11K vertices. As the expression principle axes is computed by using FaceWarehouse, why the vertex number is inconsistent? Thank you.

**Comment by YudongGuo** [comment]
Hi, for consistent with the identity part, we convert the facewarehouse topology to the basel face model topology by non rigid registration.
