### ISSUE TITLE
I need a download link

### ISSUE THREAD

**Issue by Yuri6037** [Juyong/3DFace#21]
Can you provide a direct download link for CoarseData that I can use through wget? I need this exact file: Exp_Pca.bin

**Comment by YudongGuo** [comment]
HI, I have uploaded it in this repository.

**Comment by Yuri6037** [comment]
Thanks a lot for this file. I can now continue on my thesis research.

**Comment by ZHJNCUT** [comment]
> 非常感谢这个文件。我现在可以继续我的论文研究。

I see that this data set is full of binary files. Do you know how to deal with this data set? Hope to get your answer
