### ISSUE TITLE
Could you please release google download link?

### ISSUE THREAD

**Issue by heyoon01** [Juyong/3DFace#22]
Hi!
Thanks for sharing your dataset and results to public.
I really appreciate it.
However, I could not download the files with the provided Baidu link.
I was unable to make an account from my country, 
and the link itself would not let me download any files without an account.
Could you please provide me with an google drive link?

Thanks in advance.

**Comment by heyoon01** [comment]
I need the results file, especially.

**Comment by YudongGuo** [comment]
Hi, I have uploaded it in the [results folder](https://github.com/Juyong/3DFace/tree/master/results).

**Comment by heyoon01** [comment]
Thank you so much

**Comment by ZHJNCUT** [comment]
> 太感谢了

I see that this data set is full of binary files. Do you know how to deal with this data set? Hope to get your answer
