### ISSUE TITLE
inconsistency with BFM model?

### ISSUE THREAD

**Issue by YuDeng** [Juyong/3DFace#3]
Hi, your work is great!　I've downloaded your Exp_Pca.bin and try to use it to generate expressions. I wonder why the point number is 53215 while the original BFM model has 53490 vertex. Could you show which vertex do you preserve. Besides, can you include the Eigen value of expression bases in the model?

**Comment by Yudong-Guo** [comment]
Hi, we delete the inner mouth vertices following [3DDFA](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm). You could get the index from their sharing code. Attached are std values for expression bases.
[std_exp.txt](https://github.com/Juyong/3DFace/files/2080507/std_exp.txt)

**Comment by sunjunlishi** [comment]
great  Exp

**Comment by caozhenxiang-kouji** [comment]
Hello! Where can I download Exp_Pca.bin?

**Comment by YuDeng** [comment]
Hi, you can download the CoarseData.zip. The expression PCA basis are within it.

**Comment by wxywb** [comment]
Hi, I got a version of 3dmm(which also used in 3DDFA) which uses 199 dimension vector for shape and 29 dimension for the  expression. The paper said this project uses 100 dimension for shape, I wonder how can i can get the shape basis which used in this project(shape can get from Exp_Pca.bin :) ).

**Comment by 724566247** [comment]
hello!I have a problem which I want to ask for help.The basic shape parameters of BFM is 199,but the parameters in your paper is only 100 for shape.How can we correspond them to get the shape of model?

**Comment by 724566247** [comment]
> Hi, I got a version of 3dmm(which also used in 3DDFA) which uses 199 dimension vector for shape and 29 dimension for the expression. The paper said this project uses 100 dimension for shape, I wonder how can i can get the shape basis which used in this project(shape can get from Exp_Pca.bin :) ).

Hello,I have  encounter the same question like you.Have you solved the question?

**Comment by YudongGuo** [comment]
> hello!I have a problem which I want to ask for help.The basic shape parameters of BFM is 199,but the parameters in your paper is only 100 for shape.How can we correspond them to get the shape of model?

hi, we just use the first (left) 100 components of the 199 components.

**Comment by 724566247** [comment]
> > hello!I have a problem which I want to ask for help.The basic shape parameters of BFM is 199,but the parameters in your paper is only 100 for shape.How can we correspond them to get the shape of model?
> 
> hi, we just use the first (left) 100 components of the 199 components.

thank you!I will have a try~

**Comment by zhipeng-fan** [comment]
> > hello!I have a problem which I want to ask for help.The basic shape parameters of BFM is 199,but the parameters in your paper is only 100 for shape.How can we correspond them to get the shape of model?
> 
> hi, we just use the first (left) 100 components of the 199 components.

What about the expression coefficient part?

**Comment by AsaphLightricks** [comment]
Hi,
Where can i find the triangulation of the mesh?
I tried using the ones from 3DDFA but they were not good...
Thanks
