### ISSUE TITLE
Is dataset for training Tracking CoarseNet included?

### ISSUE THREAD

**Issue by yiranran** [Juyong/3DFace#6]
It seems only datasets for training Single-image CoarseNet and for FineNet are included in this repo.
Is the dataset for training Tracking CoarseNet (extended from Single-image CoarseNet data by simulating previous frames and also including albedo and lighting parameters)  included?

**Comment by 724566247** [comment]
I have the same question.Have you get the dataset?

**Comment by YudongGuo** [comment]
Hi, dataset for tracking is not included since we randomly generate PNCC images during training.
