### ISSUE TITLE
where to find the parameters of albedo?

### ISSUE THREAD

**Issue by 724566247** [Juyong/3DFace#7]
In the paper,we can find how to calculate the 3D face geometry by p = p¯ + Aidαid + Aexpαexp.But in the dataset you give to us we can only find 100 αid parameters, we cann't find the αexp to reconstruct the albedo of the model.Is there anything wrong when I use the dataset or the parameters is inconsistency?

**Comment by YudongGuo** [comment]
> In the paper,we can find how to calculate the 3D face geometry by p = p¯ + Aidαid + Aexpαexp.But in the dataset you give to us we can only find 100 αid parameters, we cann't find the αexp to reconstruct the albedo of the model.Is there anything wrong when I use the dataset or the parameters is inconsistency?

Hi, αexp is actually 79-dim expression parameters and is just after identity parameters.
