### ISSUE TITLE
May I get the 3DMM parameters of the original picture of Fine dataset?

### ISSUE THREAD

**Issue by 724566247** [Juyong/3DFace#8]
In the dataset you given to us, we can get the 3DMM parameters of coarse dataset and the depth of fine dataset. As we can see in the paper, the 3DMM parameters of coarse dataset is derived from the first picture of fine dataset, which is the original picture.What I want to get is the 3DMM parameters of the original picture which is not rendered by the transformed 3DMM parameters.I want to use my code to get the depth of the original picture and compare with the corresponding depth you given to us in the dataset to check my code is right or wrong.Thanks for your kindness consideration.

**Comment by YudongGuo** [comment]
> In the dataset you given to us, we can get the 3DMM parameters of coarse dataset and the depth of fine dataset. As we can see in the paper, the 3DMM parameters of coarse dataset is derived from the first picture of fine dataset, which is the original picture.What I want to get is the 3DMM parameters of the original picture which is not rendered by the transformed 3DMM parameters.I want to use my code to get the depth of the original picture and compare with the corresponding depth you given to us in the dataset to check my code is right or wrong.Thanks for your kindness consideration.

Hi, you can download them from https://drive.google.com/file/d/16ZoPfLOjtykgt_tTc0q5v00pJY4Sljz3/view?usp=sharing. Note that the parameters in the text files are identity, expression, lighting, albedo, pose, respectively.
