### ISSUE TITLE
Face front index

### ISSUE THREAD

**Issue by zhongtao93** [Juyong/3DFace#9]
I find the .obj file in results only has 31513 points. Can you provide the index corresponding to BFM (which has 53490 points). Thank you very much!
![微信截图_20190618204326](https://user-images.githubusercontent.com/15263824/59682924-c6d94700-9209-11e9-9c4f-9f3e718b7f0b.png)

**Comment by YudongGuo** [comment]
Hi, the files in results folder are results of FineNet. The meshes are generated from depth maps and don't preserve the topology of BFM.

**Comment by zhongtao93** [comment]
Thank you for answering! So the 31513 points is not a subset of BFM, right?
I found that almost all other works can't hold the "eye blink" problem, that's why I want to konw how to get   an empty  eye area which can make the eye close naturally.

**Comment by YudongGuo** [comment]
Yes, it's not a subset of BFM. The empty eye are is just by deleting pixels in depth map covered by eye region in BFM model.

**Comment by zhongtao93** [comment]
Thank you! I'll close this issue
